// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: category_query.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO habit_categories (
    user_id, name, color
)
VALUES (
    $1, $2, $3
)
RETURNING id, user_id, name, color, created_at, updated_at, deleted_at, sync_version
`

type CreateCategoryParams struct {
	UserID pgtype.UUID
	Name   string
	Color  pgtype.Text
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (HabitCategory, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.UserID, arg.Name, arg.Color)
	var i HabitCategory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SyncVersion,
	)
	return i, err
}

const deleteHabitCategory = `-- name: DeleteHabitCategory :exec
UPDATE habit_categories
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteHabitCategory(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteHabitCategory, id)
	return err
}

const getHabitCategory = `-- name: GetHabitCategory :one
SELECT id, user_id, name, color, created_at, updated_at, deleted_at, sync_version FROM  habit_categories
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetHabitCategory(ctx context.Context, id pgtype.UUID) (HabitCategory, error) {
	row := q.db.QueryRow(ctx, getHabitCategory, id)
	var i HabitCategory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SyncVersion,
	)
	return i, err
}

const listHabitCategoriesByUser = `-- name: ListHabitCategoriesByUser :many
SELECT id, user_id, name, color, created_at, updated_at, deleted_at, sync_version FROM habit_categories
WHERE user_id = $1 AND deleted_at IS NUll
ORDER BY created_at DESC
`

func (q *Queries) ListHabitCategoriesByUser(ctx context.Context, userID pgtype.UUID) ([]HabitCategory, error) {
	rows, err := q.db.Query(ctx, listHabitCategoriesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HabitCategory
	for rows.Next() {
		var i HabitCategory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SyncVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHabitCategory = `-- name: UpdateHabitCategory :one
UPDATE habit_categories
SET name = $2,
    color = $3
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, user_id, name, color, created_at, updated_at, deleted_at, sync_version
`

type UpdateHabitCategoryParams struct {
	ID    pgtype.UUID
	Name  string
	Color pgtype.Text
}

func (q *Queries) UpdateHabitCategory(ctx context.Context, arg UpdateHabitCategoryParams) (HabitCategory, error) {
	row := q.db.QueryRow(ctx, updateHabitCategory, arg.ID, arg.Name, arg.Color)
	var i HabitCategory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SyncVersion,
	)
	return i, err
}

const upsertCategory = `-- name: UpsertCategory :one
INSERT INTO habit_categories (
    user_id, name, color, id
)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    color = EXCLUDED.color
RETURNING id, user_id, name, color, created_at, updated_at, deleted_at, sync_version
`

type UpsertCategoryParams struct {
	UserID pgtype.UUID
	Name   string
	Color  pgtype.Text
	ID     pgtype.UUID
}

func (q *Queries) UpsertCategory(ctx context.Context, arg UpsertCategoryParams) (HabitCategory, error) {
	row := q.db.QueryRow(ctx, upsertCategory,
		arg.UserID,
		arg.Name,
		arg.Color,
		arg.ID,
	)
	var i HabitCategory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SyncVersion,
	)
	return i, err
}
