// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RefreshToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Token     string
	UserAgent pgtype.Text
	IpAddress pgtype.Text
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

type User struct {
	ID        pgtype.UUID
	Username  string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
