// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: refresh_tokens_query.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
    user_id, token, user_agent, ip_address, expires_at
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, user_id, token, user_agent, device_id, ip_address, created_at, expires_at
`

type CreateRefreshTokenParams struct {
	UserID    pgtype.UUID
	Token     string
	UserAgent pgtype.Text
	IpAddress pgtype.Text
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.Token,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.UserAgent,
		&i.DeviceID,
		&i.IpAddress,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM refresh_tokens
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredRefreshTokens)
	return err
}

const deleteRefreshTokenByToken = `-- name: DeleteRefreshTokenByToken :exec
DELETE FROM refresh_tokens
WHERE token = $1
`

func (q *Queries) DeleteRefreshTokenByToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokenByToken, token)
	return err
}

const deleteRefreshTokenByTokenAndDeviceId = `-- name: DeleteRefreshTokenByTokenAndDeviceId :exec
DELETE FROM refresh_tokens
WHERE token = $1 AND device_id = $2
`

type DeleteRefreshTokenByTokenAndDeviceIdParams struct {
	Token    string
	DeviceID string
}

func (q *Queries) DeleteRefreshTokenByTokenAndDeviceId(ctx context.Context, arg DeleteRefreshTokenByTokenAndDeviceIdParams) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokenByTokenAndDeviceId, arg.Token, arg.DeviceID)
	return err
}

const deleteRefreshTokensByDeviceId = `-- name: DeleteRefreshTokensByDeviceId :exec
DELETE FROM refresh_tokens
WHERE device_id = $1
`

func (q *Queries) DeleteRefreshTokensByDeviceId(ctx context.Context, deviceID string) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokensByDeviceId, deviceID)
	return err
}

const deleteRefreshTokensByUserID = `-- name: DeleteRefreshTokensByUserID :exec
DELETE FROM refresh_tokens
WHERE user_id = $1
`

func (q *Queries) DeleteRefreshTokensByUserID(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokensByUserID, userID)
	return err
}

const expireAllTokensExceptDeviceId = `-- name: ExpireAllTokensExceptDeviceId :exec
UPDATE refresh_tokens
SET expires_at = NOW()
WHERE user_id = $1 AND device_id != $2
`

type ExpireAllTokensExceptDeviceIdParams struct {
	UserID   pgtype.UUID
	DeviceID string
}

func (q *Queries) ExpireAllTokensExceptDeviceId(ctx context.Context, arg ExpireAllTokensExceptDeviceIdParams) error {
	_, err := q.db.Exec(ctx, expireAllTokensExceptDeviceId, arg.UserID, arg.DeviceID)
	return err
}

const expireRefreshTokenByTokenWithDeviceId = `-- name: ExpireRefreshTokenByTokenWithDeviceId :exec
UPDATE refresh_tokens
SET expires_at = NOW()
WHERE token = $1 AND device_id = $2
`

type ExpireRefreshTokenByTokenWithDeviceIdParams struct {
	Token    string
	DeviceID string
}

func (q *Queries) ExpireRefreshTokenByTokenWithDeviceId(ctx context.Context, arg ExpireRefreshTokenByTokenWithDeviceIdParams) error {
	_, err := q.db.Exec(ctx, expireRefreshTokenByTokenWithDeviceId, arg.Token, arg.DeviceID)
	return err
}

const expireRefreshTokensByDeviceId = `-- name: ExpireRefreshTokensByDeviceId :exec
UPDATE refresh_tokens
SET expires_at = NOW()
WHERE device_id = $1
`

func (q *Queries) ExpireRefreshTokensByDeviceId(ctx context.Context, deviceID string) error {
	_, err := q.db.Exec(ctx, expireRefreshTokensByDeviceId, deviceID)
	return err
}

const getRefreshTokenByToken = `-- name: GetRefreshTokenByToken :one
SELECT id, user_id, token, user_agent, device_id, ip_address, created_at, expires_at FROM refresh_tokens
WHERE token = $1
`

func (q *Queries) GetRefreshTokenByToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.UserAgent,
		&i.DeviceID,
		&i.IpAddress,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getRefreshTokenByTokenAndDeviceId = `-- name: GetRefreshTokenByTokenAndDeviceId :one
SELECT id, user_id, token, user_agent, device_id, ip_address, created_at, expires_at FROM refresh_tokens
WHERE token = $1 AND device_id = $2
`

type GetRefreshTokenByTokenAndDeviceIdParams struct {
	Token    string
	DeviceID string
}

func (q *Queries) GetRefreshTokenByTokenAndDeviceId(ctx context.Context, arg GetRefreshTokenByTokenAndDeviceIdParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByTokenAndDeviceId, arg.Token, arg.DeviceID)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.UserAgent,
		&i.DeviceID,
		&i.IpAddress,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listRefreshTokensByUser = `-- name: ListRefreshTokensByUser :many
SELECT id, user_id, token, user_agent, device_id, ip_address, created_at, expires_at FROM refresh_tokens
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListRefreshTokensByUser(ctx context.Context, userID pgtype.UUID) ([]RefreshToken, error) {
	rows, err := q.db.Query(ctx, listRefreshTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RefreshToken
	for rows.Next() {
		var i RefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.UserAgent,
			&i.DeviceID,
			&i.IpAddress,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefreshTokensByUserAndDeviceId = `-- name: ListRefreshTokensByUserAndDeviceId :many
SELECT id, user_id, token, user_agent, device_id, ip_address, created_at, expires_at FROM refresh_tokens
WHERE user_id = $1 AND device_id = $2
ORDER BY created_at DESC
`

type ListRefreshTokensByUserAndDeviceIdParams struct {
	UserID   pgtype.UUID
	DeviceID string
}

func (q *Queries) ListRefreshTokensByUserAndDeviceId(ctx context.Context, arg ListRefreshTokensByUserAndDeviceIdParams) ([]RefreshToken, error) {
	rows, err := q.db.Query(ctx, listRefreshTokensByUserAndDeviceId, arg.UserID, arg.DeviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RefreshToken
	for rows.Next() {
		var i RefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.UserAgent,
			&i.DeviceID,
			&i.IpAddress,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllTokensExceptDeviceId = `-- name: RevokeAllTokensExceptDeviceId :exec
DELETE FROM refresh_tokens
WHERE user_id = $1 AND device_id != $2
`

type RevokeAllTokensExceptDeviceIdParams struct {
	UserID   pgtype.UUID
	DeviceID string
}

func (q *Queries) RevokeAllTokensExceptDeviceId(ctx context.Context, arg RevokeAllTokensExceptDeviceIdParams) error {
	_, err := q.db.Exec(ctx, revokeAllTokensExceptDeviceId, arg.UserID, arg.DeviceID)
	return err
}
